version: '3'

volumes:
  etc_dnsmasq:
  etc_pihole:

services:
  pihole:
    build:
      context: pihole-unbound
    image: pihole-unbound:latest
    hostname: hole
    domainname: hole.totoro.family
    environment:
      ServerIP: ${ServerIP}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
    network_mode: "host"
    volumes:
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - etc_pihole:/etc/pihole:rw
    restart: unless-stopped

